import type { CharityData } from "./types"

export const sampleCharityData: CharityData = {
  version: "1.0",
  generatedAt: "2024-11-06T00:00:00Z",
  charities: [
    {
      id: "ch-001",
      slug: "global-water-initiative",
      name: "Global Water Initiative",
      registrationNumber: "REG-2020-001",
      country: "United Kingdom",
      isIslamicCharity: false,
      categories: ["Water", "Sanitation", "Development"],
      years: [
        {
          year: 2022,
          finance: {
            incomeTrend: 6.2,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.02,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.78,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 3.5,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.82,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.15,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 6,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
        {
          year: 2023,
          finance: {
            incomeTrend: 7.1,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.04,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.84,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 4.2,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.85,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.12,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 7,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
        {
          year: 2024,
          finance: {
            incomeTrend: 8.3,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.03,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.86,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 5.0,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.76,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.12,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 8,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-002",
      slug: "islamic-relief-foundation",
      name: "Islamic Relief Foundation",
      registrationNumber: "REG-2019-042",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Humanitarian", "Emergency Aid", "Development"],
      years: [
        {
          year: 2022,
          finance: {
            incomeTrend: 5.8,
            incomeTrendRating: "Amber",
            operatingSurplusDeficit: -0.02,
            operatingSurplusDeficitRating: "Amber",
            fundraisingEfficiency: 0.71,
            fundraisingEfficiencyRating: "Amber",
            reservesCoverage: 2.8,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.79,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.18,
            fundraisingAndMarketingEfficiencyRating: "Amber",
          },
          governance: {
            numberOfTrustees: 5,
            numberOfTrusteesRating: "Amber",
            governancePoliciesUpToDate: false,
            governancePoliciesUpToDateRating: "Amber",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Adequate",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "Partially Compliant",
            gdprComplianceRating: "Amber",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
        {
          year: 2023,
          finance: {
            incomeTrend: 6.5,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.01,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.74,
            fundraisingEfficiencyRating: "Amber",
            reservesCoverage: 3.1,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.81,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.16,
            fundraisingAndMarketingEfficiencyRating: "Amber",
          },
          governance: {
            numberOfTrustees: 6,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Adequate",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
        {
          year: 2024,
          finance: {
            incomeTrend: 7.2,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.02,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.79,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 3.6,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.83,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.14,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 7,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-003",
      slug: "action-for-humanity",
      name: "Action For Humanity",
      registrationNumber: "1154881",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Humanitarian", "Emergency Aid", "Development"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: -17.01,
            incomeTrendRating: "Red",
            operatingSurplusDeficit: 0.0735,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.1952,
            fundraisingEfficiencyRating: "Amber",
            reservesCoverage: 5.66,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.9388,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.0612,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 6,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-004",
      slug: "ethar-relief",
      name: "Ethar Relief",
      registrationNumber: "1169308",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Humanitarian", "Emergency Aid", "Relief"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: 8.86,
            incomeTrendRating: "Amber",
            operatingSurplusDeficit: 0.0846,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.5078,
            fundraisingEfficiencyRating: "Red",
            reservesCoverage: 3.01,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.5612,
            charitableSpendingEfficiencyRating: "Red",
            fundraisingAndMarketingEfficiency: 0.4388,
            fundraisingAndMarketingEfficiencyRating: "Red",
          },
          governance: {
            numberOfTrustees: 4,
            numberOfTrusteesRating: "Amber",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Adequate",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "Partially Compliant",
            gdprComplianceRating: "Amber",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-005",
      slug: "doctors-worldwide",
      name: "Doctors Worldwide",
      registrationNumber: "1122671",
      country: "United Kingdom",
      isIslamicCharity: false,
      categories: ["Healthcare", "Medical", "International Development"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: 40.59,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: -0.0473,
            operatingSurplusDeficitRating: "Amber",
            fundraisingEfficiency: 0.0023,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 447.93,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.998,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.002,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 7,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-006",
      slug: "human-relief-foundation",
      name: "Human Relief Foundation",
      registrationNumber: "1126281",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Humanitarian", "Relief", "Emergency Aid"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: -46.18,
            incomeTrendRating: "Red",
            operatingSurplusDeficit: -0.0378,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.3529,
            fundraisingEfficiencyRating: "Red",
            reservesCoverage: 53.12,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.8289,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.1711,
            fundraisingAndMarketingEfficiencyRating: "Amber",
          },
          governance: {
            numberOfTrustees: 5,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: false,
            governancePoliciesUpToDateRating: "Amber",
            annualReturnsSubmittedOnTime: false,
            annualReturnsSubmittedOnTimeRating: "Red",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Adequate",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "Partially Compliant",
            gdprComplianceRating: "Amber",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-007",
      slug: "shahid-afridi-foundation",
      name: "Shahid Afridi Foundation",
      registrationNumber: "1163657",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Sports", "Community", "International Development"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: 4.73,
            incomeTrendRating: "Amber",
            operatingSurplusDeficit: 0.0116,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.0874,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 12.6,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.91,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.0874,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 3,
            numberOfTrusteesRating: "Amber",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Adequate",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-008",
      slug: "penny-appeal-uk",
      name: "Penny Appeal UK",
      registrationNumber: "1128341",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Humanitarian", "International Development", "Emergency Aid"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: -2.84,
            incomeTrendRating: "Amber",
            operatingSurplusDeficit: -0.0618,
            operatingSurplusDeficitRating: "Amber",
            fundraisingEfficiency: 0.2941,
            fundraisingEfficiencyRating: "Red",
            reservesCoverage: 5.04,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.68,
            charitableSpendingEfficiencyRating: "Amber",
            fundraisingAndMarketingEfficiency: 0.2941,
            fundraisingAndMarketingEfficiencyRating: "Red",
          },
          governance: {
            numberOfTrustees: 5,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Adequate",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "Partially Compliant",
            gdprComplianceRating: "Amber",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-009",
      slug: "indigo-volunteers",
      name: "Indigo Volunteers",
      registrationNumber: "1158459",
      country: "United Kingdom",
      isIslamicCharity: false,
      categories: ["Volunteering", "Community", "Social Welfare"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: -43.5,
            incomeTrendRating: "Red",
            operatingSurplusDeficit: -0.4476,
            operatingSurplusDeficitRating: "Red",
            fundraisingEfficiency: 0,
            fundraisingEfficiencyRating: "N/A",
            reservesCoverage: 0,
            reservesCoverageRating: "N/A",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.55,
            charitableSpendingEfficiencyRating: "Red",
            fundraisingAndMarketingEfficiency: 0,
            fundraisingAndMarketingEfficiencyRating: "N/A",
          },
          governance: {
            numberOfTrustees: 9,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: false,
            governancePoliciesUpToDateRating: "Amber",
            annualReturnsSubmittedOnTime: false,
            annualReturnsSubmittedOnTimeRating: "Red",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Inadequate",
            safeguardingAndDataProtectionPoliciesRating: "Red",
            gdprCompliance: "Partially Compliant",
            gdprComplianceRating: "Amber",
            healthAndSafetyCompliance: "Adequate",
            healthAndSafetyComplianceRating: "Amber",
          },
        },
      ],
    },
    {
      id: "ch-010",
      slug: "house-of-wisdom",
      name: "House of Wisdom",
      registrationNumber: "1211545",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Education", "Religious", "Community"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: 0,
            incomeTrendRating: "N/A",
            operatingSurplusDeficit: 0,
            operatingSurplusDeficitRating: "N/A",
            fundraisingEfficiency: 0,
            fundraisingEfficiencyRating: "N/A",
            reservesCoverage: 0,
            reservesCoverageRating: "N/A",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0,
            charitableSpendingEfficiencyRating: "N/A",
            fundraisingAndMarketingEfficiency: 0,
            fundraisingAndMarketingEfficiencyRating: "N/A",
          },
          governance: {
            numberOfTrustees: 3,
            numberOfTrusteesRating: "Amber",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Amber",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Amber",
          },
          compliance: {
            zakatPolicyCompliance: "New",
            zakatPolicyComplianceRating: "Amber",
            safeguardingAndDataProtectionPolicies: "New",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "New",
            gdprComplianceRating: "Amber",
            healthAndSafetyCompliance: "New",
            healthAndSafetyComplianceRating: "Amber",
          },
        },
      ],
    },
    {
      id: "ch-011",
      slug: "muslim-aid-uk",
      name: "Muslim Aid UK",
      registrationNumber: "1176462",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Humanitarian", "International Development", "Emergency Aid"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: 1.43,
            incomeTrendRating: "Amber",
            operatingSurplusDeficit: 0.1246,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.1335,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 4.6,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.86,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.1335,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 11,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-012",
      slug: "together-against-cancer-uk",
      name: "Together Against Cancer UK",
      registrationNumber: "1123665",
      country: "United Kingdom",
      isIslamicCharity: false,
      categories: ["Healthcare", "Cancer Support", "Medical"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: -10.45,
            incomeTrendRating: "Red",
            operatingSurplusDeficit: 0.0433,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.0815,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 10.09,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.92,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.0815,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 4,
            numberOfTrusteesRating: "Amber",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-013",
      slug: "buglife-invertebrate-conservation-trust",
      name: "Buglife – The Invertebrate Conservation Trust",
      registrationNumber: "1092293",
      country: "United Kingdom",
      isIslamicCharity: false,
      categories: ["Conservation", "Environment", "Wildlife"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: 48.87,
            incomeTrendRating: "Amber",
            operatingSurplusDeficit: 0.1044,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.53,
            fundraisingEfficiencyRating: "Red",
            reservesCoverage: 4.44,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.46,
            charitableSpendingEfficiencyRating: "Red",
            fundraisingAndMarketingEfficiency: 0.53,
            fundraisingAndMarketingEfficiencyRating: "Red",
          },
          governance: {
            numberOfTrustees: 10,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-014",
      slug: "just4children",
      name: "JUST4CHILDREN",
      registrationNumber: "1164473",
      country: "United Kingdom",
      isIslamicCharity: false,
      categories: ["Children", "Healthcare", "Medical"],
      years: [
        {
          year: 2024,
          finance: {
            incomeTrend: -1.79,
            incomeTrendRating: "Amber",
            operatingSurplusDeficit: -0.0628,
            operatingSurplusDeficitRating: "Amber",
            fundraisingEfficiency: 0.0063,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 303.12,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.99,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.0063,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 4,
            numberOfTrusteesRating: "Amber",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
  ],
  ratingLegend: {
    Green: "Meets or exceeds target threshold",
    Amber: "Close to target, needs improvement",
    Red: "Below target threshold",
    "N/A": "Not applicable",
  },
}
