import type { CharityData } from "./types"

export const sampleCharityData: CharityData = {
  version: "1.0",
  generatedAt: "2024-11-06T00:00:00Z",
  charities: [
    {
      id: "ch-001",
      slug: "global-water-initiative",
      name: "Global Water Initiative",
      registrationNumber: "REG-2020-001",
      country: "United Kingdom",
      isIslamicCharity: false,
      categories: ["Water", "Sanitation", "Development"],
      years: [
        {
          year: 2022,
          finance: {
            incomeTrend: 6.2,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.02,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.78,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 3.5,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.82,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.15,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 6,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
        {
          year: 2023,
          finance: {
            incomeTrend: 7.1,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.04,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.84,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 4.2,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.85,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.12,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 7,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
        {
          year: 2024,
          finance: {
            incomeTrend: 8.3,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.03,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.86,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 5.0,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.76,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.12,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 8,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: null,
            zakatPolicyComplianceRating: "N/A",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
    {
      id: "ch-002",
      slug: "islamic-relief-foundation",
      name: "Islamic Relief Foundation",
      registrationNumber: "REG-2019-042",
      country: "United Kingdom",
      isIslamicCharity: true,
      categories: ["Humanitarian", "Emergency Aid", "Development"],
      years: [
        {
          year: 2022,
          finance: {
            incomeTrend: 5.8,
            incomeTrendRating: "Amber",
            operatingSurplusDeficit: -0.02,
            operatingSurplusDeficitRating: "Amber",
            fundraisingEfficiency: 0.71,
            fundraisingEfficiencyRating: "Amber",
            reservesCoverage: 2.8,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.79,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.18,
            fundraisingAndMarketingEfficiencyRating: "Amber",
          },
          governance: {
            numberOfTrustees: 5,
            numberOfTrusteesRating: "Amber",
            governancePoliciesUpToDate: false,
            governancePoliciesUpToDateRating: "Amber",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Adequate",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "Partially Compliant",
            gdprComplianceRating: "Amber",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
        {
          year: 2023,
          finance: {
            incomeTrend: 6.5,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.01,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.74,
            fundraisingEfficiencyRating: "Amber",
            reservesCoverage: 3.1,
            reservesCoverageRating: "Amber",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.81,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.16,
            fundraisingAndMarketingEfficiencyRating: "Amber",
          },
          governance: {
            numberOfTrustees: 6,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Adequate",
            safeguardingAndDataProtectionPoliciesRating: "Amber",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
        {
          year: 2024,
          finance: {
            incomeTrend: 7.2,
            incomeTrendRating: "Green",
            operatingSurplusDeficit: 0.02,
            operatingSurplusDeficitRating: "Green",
            fundraisingEfficiency: 0.79,
            fundraisingEfficiencyRating: "Green",
            reservesCoverage: 3.6,
            reservesCoverageRating: "Green",
          },
          operationalCosts: {
            charitableSpendingEfficiency: 0.83,
            charitableSpendingEfficiencyRating: "Green",
            fundraisingAndMarketingEfficiency: 0.14,
            fundraisingAndMarketingEfficiencyRating: "Green",
          },
          governance: {
            numberOfTrustees: 7,
            numberOfTrusteesRating: "Green",
            governancePoliciesUpToDate: true,
            governancePoliciesUpToDateRating: "Green",
            annualReturnsSubmittedOnTime: true,
            annualReturnsSubmittedOnTimeRating: "Green",
          },
          compliance: {
            zakatPolicyCompliance: "Aligned",
            zakatPolicyComplianceRating: "Green",
            safeguardingAndDataProtectionPolicies: "Comprehensive",
            safeguardingAndDataProtectionPoliciesRating: "Green",
            gdprCompliance: "Compliant",
            gdprComplianceRating: "Green",
            healthAndSafetyCompliance: "Compliant",
            healthAndSafetyComplianceRating: "Green",
          },
        },
      ],
    },
  ],
  ratingLegend: {
    Green: "Meets or exceeds target threshold",
    Amber: "Close to target, needs improvement",
    Red: "Below target threshold",
    "N/A": "Not applicable",
  },
}
